faq_html <- readLines("docs/faq.html", warn = FALSE)
id_pattern <- '<details id="([^"]+)">'
matches <- regmatches(faq_html, regexec(id_pattern, faq_html))
ids <- unlist(lapply(matches, function(m) if (length(m) >= 2) m[2] else NULL))

slug_to_camel <- function(slug) {
  parts <- strsplit(slug, "-", fixed = TRUE)[[1]]
  parts_cap <- paste0(toupper(substring(parts, 1, 1)), substring(parts, 2))
  paste0("faq", paste0(parts_cap, collapse = ""))
}

macros <- sprintf(
  "\\newcommand{\\%s}{%d}",
  vapply(ids, slug_to_camel, character(1)),
  seq_along(ids)
)

out_path <- "latex/faq_numbers.tex"
writeLines(
  c("% Auto-generated by code/generate_faq_numbers.R. Do not edit by hand.",
    macros),
  out_path
)

cat(sprintf("Wrote %d FAQ number macros to %s\n", length(ids), out_path))
